import { getUserFromRequest } from "@/lib/auth";
import { useEffect, useState } from "react";
import Link from "next/link";

const typeOptions = {
  noOfFloors: ["G+1", "G+2", "G+3", "G+4", "G+5"],
  noOfPassenger: [6, 8, 10, 13, 18],
  doorType: ["MS FRAME COLLAPSIBLE GATE", "SS FRAME COLLAPSIBLE GATE", "MS SWING DOOR SMALL VISION", "SS SWING DOOR SMALL VISION", "MANUAL MS TELISCOPIC DOOR", "MANUAL SS TELISCOPIC DOOR", "MS CLAD AUTO DOOR", "SS CLAD AUTO DOOR", "SS HALF VISION GLASS AUTO DOOR", "SS FULL VISION GLASS AUTO DOOR", "MS HALF VISION GLASS AUTO DOOR", "MS FULL VISION GLASS AUTO DOOR"],
  cabinType: ["MS CABIN", "SS CABIN", "SS CABIN AUTO DOOR", "MS CABIN AUTO DOOR"],
  motorType: ["GEARED MOTOR", "GEAR LESS MOTOR"],
  headRoom: ["MACHINE ROOM", "MACHINE ROOM LESS"],
  doorOpening: ["600MM", "700MM", "800MM", "900MM", "1000MM", "1200MM"],
};

const initialForm = {
  serialNo: "",
  name: "",
  address: "",
  mobileNo: "",
  wellWidth: "",
  wellDepth: "",
  noOfFloors: "G+1",
  noOfPassenger: 6,
  doorType: typeOptions.doorType[0],
  cabinType: typeOptions.cabinType[0],
  motorType: typeOptions.motorType[0],
  headRoom: typeOptions.headRoom[0],
  doorOpening: typeOptions.doorOpening[0],
};

const initialCosts = {
  commonMaterial: 0,
  doorMaterial: 0,
  cabinMaterial: 0,
  motorMaterial: 0,
  ropeCost: 0,
  railCost: 0,
  additionalLfCost: 0,
  labourTransport: 75000,
  taxPercent: 18,
  marginPercent: 15,
  discountAmount: 0,
};

export async function getServerSideProps({ req }) {
  const user = await getUserFromRequest(req);
  if (!user) return { redirect: { destination: "/Adminlogin", permanent: false } };
  if (["customer", "worker", "storekeeper"].includes(user.role)) return { notFound: true };
  return { props: { user } };
}

export default function QuotationsPage({ user }) {
  const [quotations, setQuotations] = useState([]);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [canGenerate, setCanGenerate] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState(initialForm);
  const [selected, setSelected] = useState(null);
  const [costs, setCosts] = useState(initialCosts);

  async function load() {
    setLoading(true);
    setError("");
    try {
      const params = new URLSearchParams({ page: "1", pageSize: "50" });
      if (search) params.set("search", search);
      if (status) params.set("status", status);
      const res = await fetch(`/api/quotations?${params.toString()}`);
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.message || "Failed to load quotations");
      setQuotations(data.quotations || []);
      setCanGenerate(Boolean(data.canGenerate));
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    const timer = setTimeout(load, 250);
    return () => clearTimeout(timer);
  }, [search, status]); // eslint-disable-line react-hooks/exhaustive-deps

  async function createQuotation(e) {
    e.preventDefault();
    setError("");
    const res = await fetch("/api/quotations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const data = await res.json();
    if (!res.ok || !data.success) return setError(data.message || "Failed to create quotation");
    setShowCreate(false);
    setForm(initialForm);
    await load();
  }

  async function generateBoq(id) {
    setError("");
    const res = await fetch(`/api/quotations/${id}/generate-boq`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(costs) });
    const data = await res.json();
    if (!res.ok || !data.success) return setError(data.message || "Failed to generate BOQ");
    setSelected(null);
    await load();
  }

  const frontOffice = user.role === "front_office";

  return (
    <div className="min-h-screen bg-[#eef2f7] text-slate-900">
      <main className="mx-auto max-w-5xl p-4 space-y-4">
        <div className="rounded-3xl bg-[#0a649d] p-5 text-white shadow-sm">
          <p className="text-[10px] font-black uppercase tracking-widest text-white/70">Amardip Lifts ERP</p>
          <div className="mt-2 flex items-center justify-between gap-3">
            <div>
              <h1 className="text-2xl font-black">Quotations & BOQ</h1>
              <p className="text-xs text-white/75">{frontOffice ? "BOQ is generated by admin. Front office can view and share generated quotations only." : "Create drafts, generate BOQ, and print quotations."}</p>
            </div>
            {canGenerate && <button onClick={() => setShowCreate(true)} className="h-10 rounded-2xl bg-white px-4 text-xs font-black text-[#0a649d]">Create Quotation</button>}
          </div>
        </div>

        <div className="grid gap-2 sm:grid-cols-3">
          <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search quotation" className="h-11 rounded-2xl border border-slate-200 px-4 text-sm" />
          <select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-2xl border border-slate-200 px-4 text-sm">
            <option value="">All statuses</option>
            {["DRAFT", "BOQ_GENERATED", "CALCULATED", "SENT", "ACCEPTED", "REJECTED", "CONVERTED_TO_CUSTOMER"].map((item) => <option key={item}>{item}</option>)}
          </select>
          {user.role === "superadmin" && <Link className="flex h-11 items-center justify-center rounded-2xl border border-[#0a649d]/20 bg-white text-xs font-black text-[#0a649d]" href="/admin/boq-permissions">BOQ Permissions</Link>}
        </div>

        {error && <p className="rounded-2xl border border-red-100 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}
        {loading ? <p className="rounded-3xl bg-white p-8 text-center text-xs font-bold text-slate-400">Loading quotations...</p> : quotations.length === 0 ? (
          <div className="rounded-3xl bg-white p-8 text-center shadow-sm">
            <p className="text-base font-black text-slate-900">No quotations yet</p>
            <p className="mt-1 text-xs font-bold text-slate-400">Create your first lift quotation and generate BOQ pricing.</p>
            {canGenerate && <button onClick={() => setShowCreate(true)} className="mt-4 h-10 rounded-2xl bg-[#0a649d] px-4 text-xs font-black text-white">Create Quotation</button>}
          </div>
        ) : (
          <div className="space-y-3">
            {quotations.map((q) => (
              <div key={q.id} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm font-black">{q.quotationNo}</p>
                    <p className="text-xs font-bold text-slate-700">{q.customerName}</p>
                    <p className="text-[10px] text-slate-400">{q.mobileNo} · {q.noOfFloors} · {q.noOfPassenger} passenger</p>
                  </div>
                  <span className="rounded-xl bg-blue-50 px-2.5 py-1 text-[10px] font-black text-blue-700">{q.status}</span>
                </div>
                <p className="mt-2 text-xs text-slate-500">{q.doorType} / {q.cabinType}</p>
                <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3">
                  <p className="text-sm font-black text-slate-900">Rs. {q.finalPrice ?? "-"}</p>
                  <div className="flex gap-2">
                    {canGenerate && <button onClick={() => setSelected(q)} className="h-9 rounded-xl bg-[#0a649d] px-3 text-xs font-bold text-white">{q.status === "DRAFT" ? "Generate BOQ" : "Edit Cost"}</button>}
                    {q.status !== "DRAFT" && <Link href={`/admin/quotations/${q.id}/print`} className="flex h-9 items-center rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-700">Print</Link>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {showCreate && (
        <Modal title="Create Quotation" onClose={() => setShowCreate(false)}>
          <form onSubmit={createQuotation} className="space-y-3">
            {[
              ["serialNo", "S.NO", false],
              ["name", "Name", true],
              ["address", "Address", false],
              ["mobileNo", "Mobile No", true],
              ["wellWidth", "Well Width", true],
              ["wellDepth", "Well Depth", true],
            ].map(([key, label, required]) => <input key={key} required={required} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={label} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" />)}
            {Object.entries(typeOptions).map(([key, options]) => (
              <select key={key} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm">
                {options.map((option) => <option key={option} value={option}>{option}</option>)}
              </select>
            ))}
            <button className="h-11 w-full rounded-xl bg-[#0a649d] text-xs font-black text-white">Save Draft</button>
          </form>
        </Modal>
      )}

      {selected && (
        <Modal title={`Generate BOQ - ${selected.quotationNo}`} onClose={() => setSelected(null)}>
          <div className="space-y-3">
            {Object.keys(initialCosts).map((key) => (
              <input key={key} type="number" value={costs[key]} onChange={(e) => setCosts({ ...costs, [key]: e.target.value })} placeholder={key} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" />
            ))}
            <button onClick={() => generateBoq(selected.id)} className="h-11 w-full rounded-xl bg-[#0a649d] text-xs font-black text-white">Generate BOQ</button>
          </div>
        </Modal>
      )}
    </div>
  );
}

function Modal({ title, children, onClose }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4">
      <div className="w-full max-w-md rounded-3xl bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-slate-100 p-4">
          <h2 className="text-sm font-black">{title}</h2>
          <button onClick={onClose} className="h-8 w-8 rounded-full bg-slate-100 text-sm font-black">x</button>
        </div>
        <div className="max-h-[75vh] overflow-y-auto p-4">{children}</div>
      </div>
    </div>
  );
}
